### ISSUE TITLE
Wait keyword not working

### ISSUE THREAD

**Issue by chrsch** [sikuli/sikuli-slides#29]
Whenever I try to use the Wait command, it just is printed on the screen as a caption.

**Comment by doubleshow** [comment]
This issue has been addressed in the upcoming release of 1.5.

**Comment by DrKirk** [comment]
WAIT is still not working, it seems, in release 1.5.0 on a 64-bit Windows 7 Professional computer running 32-bit Sikuli Slides or 64-bit Sikuli Slides. I tried it with "WAIT" and with "WAIT 30 seconds" but saw no waiting.

**Comment by doubleshow** [comment]
The WAIT command takes a rectangle on an image. The meaning is to wait for a target to appear. The DELAY command takes a number and just delay for that much time. 

Which do you want to accomplish?

**Comment by DrKirk** [comment]
@doubleshow -- Thank you for your prompt response!

I wanted the WAIT functionality, but I confused the documentation about the PAUSE action with the documentation about the WAIT action. I thought that I could put a WAIT action on the same slide as, say, a CLICK action, but, per your explanation -- which matches the Sikuli Slides documentation -- I was wrong. Now I see that I need a separate slide just for WAIT, with a bounding rectangle around the image pattern to be found.

However, I noticed at http://slides.sikuli.org/docs/actions/ that one is supposed to be able to say "WAIT 10 seconds" to tell Sikuli Slides to wait no more than 10 seconds to find an image pattern. Is this extra feature for the WAIT action still in existence?

Thanks again!
